version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito
      POSTGRES_DB: avito_banner_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: avito@example.com
      PGADMIN_DEFAULT_PASSWORD: avito
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"

volumes:
  pg_data:
  pgadmin_data:
